import fs from "node:fs/promises";

/**
 * Applies the AI-generated fix to the specified file if changes are detected.
 *
 * @param filePath - Absolute or relative path to the file being updated.
 * @param fixedCode - Updated source code generated by the AI.
 * @returns A promise that resolves to `true` if the file was modified, or `false` if no changes were necessary.
 * @throws Will throw an error if the file cannot be read from or written to.
 */
export async function applyFix(
    filePath: string,
    fixedCode: string
): Promise<boolean> {
    const originalCode = await fs.readFile(filePath, "utf-8");

    if (originalCode === fixedCode) {
        console.log("ℹ️ No changes detected.");
        return false;
    }

    await fs.writeFile(filePath, fixedCode);

    return true;
}