import { Octokit } from "@octokit/rest";
import dotenv from "dotenv";

dotenv.config();

const octokit = new Octokit({
    auth: process.env.GITHUB_TOKEN,
});

const owner = process.env.GITHUB_OWNER!;
const repo = process.env.GITHUB_REPO!;


/**
 * Creates a GitHub pull request for the AI-generated fix.
 *
 * @param branchName - Name of the source branch containing the fix.
 */
export async function createPullRequest(branchName: string) {
    const response = await octokit.pulls.create({
        owner,
        repo,
        title: "fix: AI generated runtime fix",
        head: branchName,
        base: process.env.GITHUB_BASE_BRANCH ?? "dev",
        body: `
## 🤖 AI Generated Fix

This pull request was automatically generated by the AI Self-Healing Developer Assistant.

### Changes
- Detected a runtime error
- Generated a fix using Gemini AI
- Applied and committed the fix automatically
`,
    });

    console.log(`🔀 Pull Request created: ${response.data.html_url}`);
}