import fs from "node:fs/promises";
import type { ErrorLog } from "./types.js";
import type { StackFrame } from "./types.js";

/**
 * Reads the contents of a source file as a UTF-8 encoded string.
 *
 * @param filePath - Absolute or relative path to the source file.
 * @returns A promise that resolves with the file contents as a string.
 * @throws Will throw an error if the file does not exist or cannot be read.
 */
export const readSourceFile = async (
    filePath: string
): Promise<string> => {
    return await fs.readFile(filePath, "utf-8");
};

/**
 * Applies the AI-generated fix to the specified file if changes are detected.
 *
 * @param filePath - Absolute or relative path to the file being updated.
 * @param fixedCode - Updated source code generated by the AI.
 * @returns A promise that resolves to `true` if the file was modified, or `false` if no changes were necessary.
 * @throws Will throw an error if the file cannot be read from or written to.
 */
export async function applyFix(
    filePath: string,
    fixedCode: string
): Promise<boolean> {
    const originalCode = await fs.readFile(filePath, "utf-8");

    if (originalCode === fixedCode) {
        console.log("ℹ️ No changes detected.");
        return false;
    }

    await fs.writeFile(filePath, fixedCode);

    return true;
}


/**
 * Reads and returns the most recent error log from the log file.
 *
 * @param logFile - Path to the log file.
 * @returns The latest parsed error log.
 */
export const getLatestLog = async (
    logFile: string
): Promise<ErrorLog> => {
    const fileContent = await fs.readFile(logFile, "utf-8");

    const logs = fileContent.trim().split("\n");

    const latestLog = logs.at(-1);

    if (!latestLog) {
        throw new Error(`No logs found in ${logFile}`);
    }

    return JSON.parse(latestLog) as ErrorLog;
};

/**
 * Extracts the file path, line, and column from a stack trace.
 *
 * @param stack - Error stack trace.
 * @returns Parsed stack frame or `null` if parsing fails.
 */
export const parseStackTrace = (
    stack: string
): StackFrame | null => {
    const match = stack.match(/\((.*):(\d+):(\d+)\)/);

    if (!match || !match[1] || !match[2] || !match[3]) {
        return null;
    }

    return {
        filePath: match[1],
        line: Number(match[2]),
        column: Number(match[3]),
    };
};